import { MigrationInterface, QueryRunner } from "typeorm";

export class LibraryCreateTable1679534437979 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
          CREATE TABLE
          library (
            "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            "description" VARCHAR(50) NOT NULL,
            
            created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,

            CONSTRAINT PK_library PRIMARY KEY ("id")
          );`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE library;`);
    }
}
