import { MigrationInterface, QueryRunner } from 'typeorm';

export class UserCreateTable1680738977433 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE
      "user" (
        "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "name" VARCHAR(50) NOT NULL,
        "email" VARCHAR(50) NOT NULL,
        "password" VARCHAR(100),
        "language" VARCHAR(30) CHECK (LANGUAGE IN  ('en', 'pt-br')) default 'en',

        created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
        
        CONSTRAINT PK_user PRIMARY KEY ("id"),
        CONSTRAINT UK_user_email UNIQUE ("email")
      );`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "user";`);
  }
}
