import { MigrationInterface, QueryRunner } from "typeorm";

export class LibraryUserCreateTable1680742947407 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
          CREATE TABLE
          library_user (
              "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
              "userId" INT,
              "libraryId" INT,
              "email_verified_at" TIMESTAMP(0) default NULL,

              created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,

              CONSTRAINT PK_library_user PRIMARY KEY ("id"),
              CONSTRAINT FK_library_user FOREIGN KEY ("libraryId") references library ("id") ON DELETE CASCADE,
              CONSTRAINT FK_user_library FOREIGN KEY ("userId") references "user" ("id") ON DELETE CASCADE
          );`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE library_user;`);
    }
}
