import { MigrationInterface, QueryRunner } from 'typeorm';

export class PersonCreateTable1681776270324 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE
        person (
          "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
          "name" VARCHAR(250) NOT NULL,
          "document" VARCHAR(50),
          "zip_code" VARCHAR(15),
          "state" VARCHAR(30),
          "city" VARCHAR(30),
          "district" VARCHAR(100),
          "street" VARCHAR(100),
          "number" VARCHAR(5),
          "email" VARCHAR(50),
          "phone" VARCHAR(20),
          "obs" TEXT,
          "country" VARCHAR(50),
          "libraryId" INT NOT NULL,

          created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
          
          CONSTRAINT PK_person PRIMARY KEY ("id"),
          CONSTRAINT FK_library_person FOREIGN KEY ("libraryId") REFERENCES library ("id") ON DELETE CASCADE
        );`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE person;`);
  }
}
