import { MigrationInterface, QueryRunner } from 'typeorm';

export class PublisherCreateTable1681084447979 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE
        publisher (
          "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
          "name" VARCHAR(50) NOT NULL,
          "country" VARCHAR(30),
          "libraryId" INT NOT NULL,

          created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
          
          CONSTRAINT PK_publisher PRIMARY KEY ("id"),
          CONSTRAINT FK_library_publisher FOREIGN KEY ("libraryId") REFERENCES library ("id") ON DELETE CASCADE
        );`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE publisher;`);
  }
}
