import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateResetTokenTable1760897406985 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
          CREATE TABLE
            reset_tokens (
                "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "token" TEXT NOT NULL,
                "expiresAt" TIMESTAMP(0) NOT NULL,
                "used" BOOLEAN NOT NULL DEFAULT FALSE,
                "type" VARCHAR(30) CHECK (TYPE IN  ('E', 'S')),
                "userId" INT NOT NULL,

                created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                
                CONSTRAINT PK_reset_password PRIMARY KEY ("id"),
                CONSTRAINT FK_reset_tokens_user FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE
            );
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE reset_tokens;`);
    }

}
